app/models/post.py
from datetime import datetime

from ..extensions import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(250))
    teacher = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'))
    student = db.Column(db.Integer)
    date = db.Column(db.DateTime, default=datetime.utcnow)

app/models/user.py
from ..extensions import db, login_manager
from datetime import datetime
from flask_login import UserMixin
from .post import Post

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))    
    login = db.Column(db.String(50))
    avatar = db.Column(db.String(200))
    password = db.Column(db.String(200))
    date = db.Column(db.DateTime, default=datetime.utcnow)
    status = db.Column(db.String(50))
    posts = db.relationship(Post, backref='author')

app/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, SubmitField, FileField, ValidationError, SelectField
from wtforms.validators import Length, DataRequired, EqualTo
from flask_wtf.file import FileAllowed

from app.models.user import User


class RegistrationForm(FlaskForm):
    avatar = FileField('Avatar' , validators=[FileAllowed(['jpg', 'png'])])
    name = StringField('Name', validators=[DataRequired(), Length(min=2, max=20)])
    login = StringField('Login', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Submit')

    def validate_login(self, login):
        user = User.query.filter_by(login=login.data).first()
        if user:
            raise ValidationError('This login is exist. You should use another login!')
        
class LoginForm(FlaskForm):
    """Form to log in users"""
    login = StringField('Login', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Log in')

class StudentForm(FlaskForm):
    student = SelectField('student', choices=[], render_kw={'class':'form-control'})

        
        

app/__init__.py
from flask import Flask
from .extensions import db, migrate, login_manager, assets
from .config import Config
from .routes.user import user
from .routes.post import post



def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    

    app.register_blueprint(user)
    app.register_blueprint(post)
    
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    assets.init_app(app)

    # Login Manager
    login_manager.login_view = 'user.login'
    login_manager.login_message = 'You can\'t get an access to this page. You should first log in!'
    login_manager.login_message_category = 'info'

    #Assets
    

    with app.app_context():
        db.create_all()
        
    return app

app/routes.py
from flask import Blueprint
from .extensions import db
from app.models.user import User

user = Blueprint('user', __name__)

@user.route('/user/<name>')
def creqte_user(name):
    user = User(name=name)
    db.session.add(user)
    db.session.commit()
    return 'User created successfully!'

app/routes/post.py
from crypt import methods
from flask_login import login_required
from flask import Blueprint, render_template, request, redirect
from ..extensions import db
from app.models.post import Post
from ..models.user import User
from ..forms import StudentForm

post = Blueprint('post', __name__)

@post.route('/')
def all():
    posts = Post.query.order_by(Post.date).all()
    return render_template('post/all.html', posts=posts, user=User)

@post.route('/post/create', methods=['GET', 'POST'])
@login_required
def create():
    form = StudentForm()
    form.student.choices = [(s.id, s.name) for s in User.query.filter_by(status='user')]

    if request.method == 'POST':
        teacher = request.form['teacher']
        subject = request.form.get('subject')
        student = request.form.get('student')
        
        date = request.form.get('date')

        new_post = Post(teacher=teacher, subject=subject, student=student, date=date)
        try:
            db.session.add(new_post)
            db.session.commit()
            print('post created')

            return redirect('/')
        except Exception as e:
            print(str(e))
    else:
        return render_template('post/create.html', form=form)


@post.route('/post/<int:id>/update', methods=['GET', 'POST'])
@login_required
def update(id):
    result = Post.query.get(id)
    form = StudentForm()
    
    form.student.choices = [(s.id, s.name) for s in User.query.filter_by(status='user')]
    
    if request.method == 'POST':
        result.subject = request.form.get('subject')
        result.student = request.form.get('student')        
        try:
            db.session.commit()
            print('post updated')

            return redirect('/')
        except Exception as e:
            print(str(e))
    else:
        return render_template('post/update.html', post=result, form=form)
    

@post.route('/post/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete(id):
    result = Post.query.get(id)   
    try:
        db.session.delete(result)
        db.session.commit()
        print('post deleted')

        return redirect('/')
    except Exception as e:
        print(str(e))
    

app/routes/routes.py
from flask import Blueprint
from ..extensions import db
from app.models.user import User

user = Blueprint('user', __name__)

@user.route('/user/<name>')
def creqte_user(name):
    user = User(name=name)
    db.session.add(user)
    db.session.commit()
    return 'User created successfully!'

app/routes/user.py
from flask import Blueprint, render_template, redirect, flash, request, url_for
from flask_login import login_user, logout_user
from app.functions import save_picture
from ..extensions import db, bcrypt
from app.models.user import User
from ..forms import RegistrationForm, LoginForm

user = Blueprint('user', __name__)


@user.route('/user/register', methods=['POST', 'GET'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        if form.avatar.data:
            avatar_filename = save_picture(form.avatar.data)
        else:
            # Handle the case where no data is provided
            avatar_filename = None
            print("No avatar data provided.")
        user = User(name=form.name.data, login=form.login.data, avatar=avatar_filename, password=hashed_password)
        try:
            db.session.add(user)
            db.session.commit()        
            flash(f"You are registered!", "success")
            return redirect(url_for('user.login'))
        except Exception as e:
            print(e)
            flash(f"Error of registration!", "danger")
            
    return render_template('user/register.html', form=form)


@user.route('/user/login', methods=['POST', 'GET'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(login=form.login.data).first()    
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')     
            flash(f"Congrutilations, you are logined!", "success") 
            return redirect(next_page) if next_page else redirect(url_for('post.all'))
        else:                    
            flash(f"Error of login!", "danger")
    
    return render_template('user/login.html', form=form)


@user.route('/user/logout', methods=['POST','GET'])
def logout():
    logout_user()
    return redirect(url_for('post.all'))

app/templates/main/__flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    {% for category, message in messages %}
        <div class="alert alert-{{category}}">
            {{message}}
        </div>
    {% endfor %}
{% endif %}
{% endwith %}
<!-- Flash message -->

app/templates/main/__footer.html
<footer class="py-3 my-4 text-bg-dark">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-white">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-white">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-white">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-white">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-white">About</a></li>
    </ul>
    <p class="text-center text-body-white">© 2024 Company, Inc</p>
  </footer>

app/templates/main/__header.html
<header class="header p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <img class="header_img" src="{{ url_for('static', filename='img/logo.png') }}" alt="Mongol Empire" />
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{{ url_for('post.all') }}" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="{{ url_for('post.create') }}" class="nav-link px-2 text-white">Post Create</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>
<!--
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>
-->
        <div class="text-end">    
          {% if current_user.is_authenticated %}
          <span>Welcome, {{ current_user.login }} </span>
          <a href="{{ url_for('user.logout') }}" class="btn btn-warning">Logout</a>   
          {% else %}
          <a href="{{ url_for('user.login') }}" class="btn btn-warning">Login</a>   
          <a href="{{ url_for('user.register') }}" class="btn btn-warning">Sign-up</a>
          {% endif %}          
        </div>
      </div>
    </div>
  </header>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<!-- Additional metadata, stylesheets, or scripts can be included here -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/libs/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='fontawesome/css/all.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<title>{% block title %} {% endblock %}</title>

</head>
<body>
    <!-- Header -->
            {% include 'main/__header.html' %} 
    <div class="page">
        <main class="content">
            <h1>{{ self.title() }}</h1>
            <!-- Flash message -->
                {% include 'main/__flash.html' %}
            {% block content %} {% endblock %}
        </main>
        <!-- Footer -->
            {% include 'main/__footer.html' %}
    </div>
</body>
<script src="{{ url_for('static', filename='fontawesome/js/all.js') }}"></script>
<script src="{{ url_for('static', filename='js/libs/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/app.js') }}"></script>
</html>

app/templates/main/index.html
{% extends 'main/base.html' %}


{% block title %}
Home
{% endblock %}


{% block content %}




{% endblock %}

app/templates/post/all.html
{% extends 'main/base.html' %}


{% block title %}
Posts
{% endblock %}


{% block content %}

<div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Teacher</th>
      <th scope="col">Subject</th>
      <th scope="col">Student</th>
      {% if current_user.is_authenticated %}
        <th scope="col">Actions</th>
        {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for post in posts %}
        <tr>
         
          <td>
            <img width="50" src="{{url_for('static', filename='upload/'+post.author.avatar)}}" alt="">
            {{ post.author.name }}</td>
          <td>{{ post.subject }}</td>
          <td>
            {% with student = user.query.get(post.student) %}
              {{student.name}}
            {% endwith %}</td>


          
          <td>
            {% if current_user.is_authenticated and post.author.id == current_user.id %}
              <a class="btn btn-sm btn-secondary" href="{{ url_for('post.update', id=post.id) }}"><span class="fa fa-edit"></span></a>
              <a class="btn btn-sm btn-danger" href="{{ url_for('post.delete', id=post.id) }}"><span class="fa fa-trash"></span></a>
            {% endif %}
        </td>   
        </tr>
    {% endfor %}
  </tbody>
</table>
</div>


{% endblock %}

app/templates/post/create.html
{% extends 'main/base.html' %}

{% block title %}
Create post
{% endblock %}


{% block content %}

<form class="form-control d-flex flex-column gap-2" method="post">
    <input class="form-control" type="text" name="teacher"  placeholder="Full name of teacher">
    <input class="form-control" type="text" name="subject" placeholder="Subject">
    {{form.student }} 
    <input class="form-control" type="date" name="date">
    <input class="btn btn-success" type="submit" value="Submit">
</form>


{% endblock %}

app/templates/post/update.html
{% extends 'main/base.html' %}

{% block title %}
Update post number {{ post.id }}
{% endblock %}


{% block content %}

<form class="form-control d-flex flex-column gap-2" method="post">
    <input value="{{ post.teacher }}" class="form-control" type="text" name="teacher"  placeholder="Full name of teacher">
    <input value="{{ post.subject }}" class="form-control" type="text" name="subject" placeholder="Subject">
    {{form.student }} 
    <input class="btn btn-success" type="submit" value="Submit">
</form>


{% endblock %}

app/templates/user/login.html
{% extends 'main/base.html' %}


{% block title %}
Authentification
{% endblock %}


{% block content %}
<form method="post"  class="form-control d-flex flex-column gap-2">
 
  {{form.csrf_token}}
 
  {{form.login.label(class="form-label")}}
    {% if form.login.errors %}
      <div class="invalid-feedback" style="display: block!important;">
        {% for error in form.login.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
    {% endif %}
  {{form.login(class="form-control")}}
 
  {{form.password.label(class="form-label")}}
  {{form.password(class="form-control")}} 
    
  <div class="d-flex flex-row justify-content-center gap-2">{{form.remember.label(class="form-label")}}
    {{form.remember(class="form-check")}}</div>

  {{form.submit(class="btn btn-warning")}}

</form>
        

{% endblock %}

app/templates/user/register.html
{% extends 'main/base.html' %}


{% block title %}
Registration
{% endblock %}


{% block content %}
<form method="post" enctype="multipart/form-data" class="form-control d-flex flex-column gap-2">
 
  {{form.csrf_token}}
  {{form.name.label(class="form-label")}}
  {{form.name(class="form-control")}}
  {{form.login.label(class="form-label")}}
    {% if form.login.errors %}
      <div class="invalid-feedback" style="display: block!important;">
        {% for error in form.login.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
    {% endif %}
  {{form.login(class="form-control")}}
  {{form.avatar.label(class="form-label")}}
  {{form.avatar(class="form-control")}}
  {{form.password.label(class="form-label")}}
  {{form.password(class="form-control")}}
  {{form.confirm_password.label(class="form-label")}}
  {{form.confirm_password(class="form-control")}}
  {{form.submit(class="btn btn-warning")}}

</form>
        

{% endblock %}